### ISSUE TITLE
Deploy swan on docker error

### ISSUE THREAD

**Issue by devopsING2** [swan-io/swan-partner-frontend#261]
I tried to serve the application in a docker environment using the dockerfile already present on the repository, following all the steps described in the swan documentation.
Install yarn, which is required to mangage the monorepository.
`$ yarn`

Bundle the client applications and the server in ./server in production with the following command:
`$ yarn build`

Dockerize
Create a Docker image from the built files:
`$ docker build -t swan .`

**You get this error when you try to launch the application image:**

```
> @swan-io/frontend-server@1.0.30 start
swan-partner-frontend-server-1  | > node -r ./dist/tracing.js ./dist/index.js
swan-partner-frontend-server-1  | 
swan-partner-frontend-server-1  | Error: Cannot find module 'vite'
swan-partner-frontend-server-1  | Require stack:
swan-partner-frontend-server-1  | - /app/dist/client/devServer.js
swan-partner-frontend-server-1  | - /app/dist/app.js
swan-partner-frontend-server-1  | - /app/dist/index.js
swan-partner-frontend-server-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
swan-partner-frontend-server-1  |     at Module._load (node:internal/modules/cjs/loader:922:27)
swan-partner-frontend-server-1  |     at Module.require (node:internal/modules/cjs/loader:1143:19)
swan-partner-frontend-server-1  |     at require (node:internal/modules/cjs/helpers:110:18)
swan-partner-frontend-server-1  |     at /app/dist/client/devServer.js:38:78
swan-partner-frontend-server-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
swan-partner-frontend-server-1  |     at async createViteDevServer (/app/dist/client/devServer.js:38:30)
swan-partner-frontend-server-1  |     at async Promise.all (index 0)
swan-partner-frontend-server-1  |     at async startDevServer (/app/dist/client/devServer.js:60:38)
swan-partner-frontend-server-1  |     at async start (/app/dist/app.js:610:37) {
swan-partner-frontend-server-1  |   code: 'MODULE_NOT_FOUND',
swan-partner-frontend-server-1  |   requireStack: [
swan-partner-frontend-server-1  |     '/app/dist/client/devServer.js',
swan-partner-frontend-server-1  |     '/app/dist/app.js',
swan-partner-frontend-server-1  |     '/app/dist/index.js'
swan-partner-frontend-server-1  |   ]
swan-partner-frontend-server-1  | }
swan-partner-frontend-server-1 exited with code 1

```

**Comment by zoontek** [comment]
@devopsING2 Hi!

Did you switched `NODE_ENV="development"` to `NODE_ENV="production"` before running `yarn build` and `docker build -t swan .`?

**Comment by bloodyowl** [comment]
I think the issue comes from the fact the provided `NODE_ENV` isn't `"production"`, triggering the development mode.

you can find the list of necessary env variables here: https://swan-io.github.io/swan-partner-frontend/build-deploy#required-environment-variables

**Comment by devopsING2** [comment]
Thanks, yes that was the problem
